#!/bin/bash
BASE_VERSION=$(circleci env subst "${BASE_VERSION}")
PIPELINE_NUMBER=$(circleci env subst "${PIPELINE_NUMBER}")

echo "BASE_VERSION: $BASE_VERSION"
echo "PIPELINE_NUMBER: $PIPELINE_NUMBER"
echo "CIRCLE_BRANCH: $CIRCLE_BRANCH"

VERSION_PREFIX=$BASE_VERSION.$PIPELINE_NUMBER

if [ "$CIRCLE_BRANCH" == "main" ]; then 
    VERSION_SUFFIX=test; 
else 
    VERSION_SUFFIX=$CIRCLE_BRANCH;
    NUGET_VERSION_SUFFIX=$CIRCLE_BRANCH; 
fi

FULL_VERSION=$VERSION_PREFIX-$VERSION_SUFFIX

{
    echo "export VERSION_PREFIX=$VERSION_PREFIX"
    echo "export NUGET_VERSION_SUFFIX=$NUGET_VERSION_SUFFIX"
    echo "export FULL_VERSION=$FULL_VERSION"
} >> "$BASH_ENV"